use master
DECLARE @dbname nvarchar(128)
SET @dbname = N'SORIA_TPC'

IF(EXISTS(SELECT name FROM master.dbo.sysdatabases WHERE('[' + name + ']' = @dbname
OR name = @dbname)))
drop database SORIA_TPC

GO
use master
GO
CREATE DATABASE SORIA_TPC
GO
USE SORIA_TPC
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 01/05/2019 11:00:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET DATEFORMAT 'YMD'
GO

CREATE TABLE [dbo].[PERFILES](
	[ID]		   [BIGINT] NOT NULL IDENTITY(1,1),
	[NOMBRE]	   [VARCHAR](30)NOT NULL CHECK(NOMBRE= 'Docente' or NOMBRE= 'Administrador' or NOMBRE= 'Secretario' or NOMBRE= 'Asistente social'or NOMBRE= 'Director'),
CONSTRAINT [PK_PERFILES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DIRECCIONES](
	[ID]		   [BIGINT] NOT NULL IDENTITY(1,1),
	[CALLE]		   [VARCHAR](50)NOT NULL,
	[NUMERO]	   [VARCHAR](7)NOT NULL,
	[DEPARTAMENTO] [VARCHAR](2) NULL,
	[PISO]		   [VARCHAR](2) NULL,
CONSTRAINT [PK_DIRECCIONES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PERSONAS](
	[ID]		   [BIGINT] NOT NULL IDENTITY(1,1),
	[NOMBRE]	   [VARCHAR](50)NOT NULL,
	[APELLIDO]	   [VARCHAR](50)NOT NULL,
	[DNI]		   [VARCHAR](15)NOT NULL,
	[NACIMIENTO]   [DATE] NOT NULL CHECK(DATEDIFF(DAY,NACIMIENTO,GETDATE())>0),
	[EMAIL]		   [VARCHAR](60)NOT NULL,
	[IDDIRECCION]  [BIGINT] NULL FOREIGN KEY REFERENCES DIRECCIONES(ID),
 CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DOCENTES](
	[ID]		   [BIGINT] NOT NULL IDENTITY(1,1),
	[IDPERSONA]	   [BIGINT] NOT NULL FOREIGN KEY REFERENCES PERSONAS(ID),
	[NIVEL]		   [VARCHAR](30) NOT NULL CHECK(NIVEL='Primaria' or NIVEL='Secundaria' or NIVEL='Facultad' or NIVEL='Universidad')
CONSTRAINT [PK_DOCENTES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ALUMNOS](
	[ID]		   [BIGINT] NOT NULL IDENTITY(1,1),
	[IDPERSONA]	   [BIGINT] NOT NULL FOREIGN KEY REFERENCES PERSONAS(ID),
	[IDTUTOR]	   [BIGINT] NOT NULL FOREIGN KEY REFERENCES PERSONAS(ID),
CONSTRAINT [PK_ALUMNOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USUARIOS](
	[IDPERSONA]	   [BIGINT] NOT NULL FOREIGN KEY REFERENCES PERSONAS(ID),
	[IDPERFIL]	   [BIGINT] NOT NULL FOREIGN KEY REFERENCES PERFILES(ID),
	[USERNAME]	   [VARCHAR](30)NOT NULL,
	[CONTRASEÑA]   [VARCHAR](30)NOT NULL,
	[INICIO]       [DATE]NOT NULL,
CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[IDPERSONA],[IDPERFIL] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ESTABLECIMIENTOS](
	[ID]		   [BIGINT] NOT NULL IDENTITY(1,1),
	[NOMBRE]	   [VARCHAR](50) NOT NULL,
	[NUMERO]	   [INT] NULL,
	[NIVEL]		   [VARCHAR](30) NOT NULL CHECK(NIVEL='Primaria' or NIVEL='Secundaria' or NIVEL='Facultad' or NIVEL='Universidad') ,
	[IDDIRECCION]  [BIGINT] NOT NULL FOREIGN KEY REFERENCES DIRECCIONES(ID),
CONSTRAINT [PK_ESTABLECIMIENTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CURSOS](
	[ID]	  [BIGINT] NOT NULL IDENTITY(1,1),
	[NOMBRE]  [VARCHAR](50)NOT NULL,
	[CICLO]   [TINYINT] NOT NULL DEFAULT 1 ,
	[ABIERTO] [BIT] NOT NULL DEFAULT 0 ,
CONSTRAINT [PK_CURSOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PERSONASXESTABLECIMIENTO](
	[ID]				[BIGINT] NOT NULL IDENTITY(1,1),
	[IDESTABLECIMIENTO]	[BIGINT] NOT NULL FOREIGN KEY REFERENCES ESTABLECIMIENTOS(ID),
	[IDPERSONA]			[BIGINT] NOT NULL FOREIGN KEY REFERENCES PERSONAS(ID),
CONSTRAINT [PK_PERSONASXESTABLECIMIENTO] PRIMARY KEY CLUSTERED 
(
	[IDESTABLECIMIENTO],[IDPERSONA] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CURSOSXESTABLECIMIENTO](
	[ID]				[BIGINT] NOT NULL IDENTITY(1,1),
	[IDESTABLECIMIENTO]	[BIGINT] NOT NULL FOREIGN KEY REFERENCES ESTABLECIMIENTOS(ID),
	[IDCURSO]			[BIGINT] NOT NULL FOREIGN KEY REFERENCES CURSOS(ID),
	[IDDOCENTE]			[BIGINT] NULL FOREIGN KEY REFERENCES DOCENTES(ID),
CONSTRAINT [PK_CURSOSXESTABLECIMIENTO] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ASISTENCIAS](
	[ID]	   [BIGINT] NOT NULL IDENTITY(1,1),
	[IDALUMNO] [BIGINT] NOT NULL FOREIGN KEY REFERENCES ALUMNOS(ID),
	[IDCXE]    [BIGINT] NOT NULL FOREIGN KEY REFERENCES CURSOSxESTABLECIMIENTO(ID),
	[FECHA]    [DATE]   NOT NULL,
 CONSTRAINT [PK_ASISTENCIAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ALUMNOSXCURSO](
	[ID]	   [BIGINT] NOT NULL IDENTITY(1,1),
	[IDCXE]    [BIGINT] NOT NULL FOREIGN KEY REFERENCES CURSOSxESTABLECIMIENTO(ID),
	[IDALUMNO] [BIGINT] NOT NULL FOREIGN KEY REFERENCES ALUMNOS(ID),
CONSTRAINT [PK_ALUMNOSXCURSO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DOCENTESXCURSO](
	[ID]	    [BIGINT] NOT NULL IDENTITY(1,1),
	[IDCURSO]	[BIGINT] NOT NULL FOREIGN KEY REFERENCES CURSOS(ID),
	[IDDOCENTE]	[BIGINT] NOT NULL FOREIGN KEY REFERENCES DOCENTES(ID),
CONSTRAINT [PK_DOCENTESXCURSO] PRIMARY KEY CLUSTERED 
(
	[IDCURSO],[IDDOCENTE] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[NOTASXCURSO](
	[ID]	    [BIGINT]  NOT NULL IDENTITY(1,1),
	[IDCXE]	    [BIGINT]  NOT NULL FOREIGN KEY REFERENCES CURSOSxESTABLECIMIENTO(ID),
	[IDALUMNO]  [BIGINT]  NOT NULL FOREIGN KEY REFERENCES ALUMNOS(ID),
	[ANIO]		[SMALLINT] NOT NULL,
	[NOTA1]	    [TINYINT] NULL CHECK(NOTA1=0 or NOTA1=1 or NOTA1=2 or NOTA1=3 OR NOTA1=4 or NOTA1=5 or NOTA1=6 or NOTA1=7 OR NOTA1=8 or NOTA1=9 or NOTA1=10),
	[NOTA2]	    [TINYINT] NULL CHECK(NOTA2=0 or NOTA2=1 or NOTA2=2 or NOTA2=3 OR NOTA2=4 or NOTA2=5 or NOTA2=6 or NOTA2=7 OR NOTA2=8 or NOTA2=9 or NOTA2=10),
	[NOTA3]	    [TINYINT] NULL CHECK(NOTA3=0 or NOTA3=1 or NOTA3=2 or NOTA3=3 OR NOTA3=4 or NOTA3=5 or NOTA3=6 or NOTA3=7 OR NOTA3=8 or NOTA3=9 or NOTA3=10),
	[NOTA4]	    [TINYINT] NULL CHECK(NOTA4=0 or NOTA4=1 or NOTA4=2 or NOTA4=3 OR NOTA4=4 or NOTA4=5 or NOTA4=6 or NOTA4=7 OR NOTA4=8 or NOTA4=9 or NOTA4=10),
	[OBSERVACION] [VARCHAR](500) NULL,
CONSTRAINT [PK_NOTASXCURSO] PRIMARY KEY CLUSTERED 
(
	[IDCXE],[IDALUMNO],[ANIO] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CALIFICACIONESXCURSO](
	[ID]	    [BIGINT]  NOT NULL IDENTITY(1,1),
	[IDCXE]	    [BIGINT]  NOT NULL FOREIGN KEY REFERENCES CURSOSxESTABLECIMIENTO(ID),
	[IDALUMNO]  [BIGINT]  NOT NULL FOREIGN KEY REFERENCES ALUMNOS(ID),
	[ANIO]		[INT]     NOT NULL,
	[NOTA1]	    [VARCHAR](2) NOT NULL CHECK(NOTA1='' or NOTA1='R' or NOTA1='B' or NOTA1='MB' or NOTA1='S') DEFAULT '',
	[NOTA2]	    [VARCHAR](2) NOT NULL CHECK(NOTA2='' or NOTA2='R' or NOTA2='B' or NOTA2='MB' or NOTA2='S') DEFAULT '',
	[NOTA3]	    [VARCHAR](2) NOT NULL CHECK(NOTA3='' or NOTA3='R' or NOTA3='B' or NOTA3='MB' or NOTA3='S') DEFAULT '',
	[OBSERVACION] [VARCHAR](500) NULL,
CONSTRAINT [PK_CALIFICACIONESXCURSO] PRIMARY KEY CLUSTERED 
(
	[IDCXE],[IDALUMNO],[ANIO] ASC
)WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
---------------------------------------------------INSERT---------------------------------------------------------------------

INSERT INTO SORIA_TPC.dbo.PERFILES (NOMBRE ) values ('Administrador')
INSERT INTO SORIA_TPC.dbo.PERFILES (NOMBRE ) values ('Asistente social')
INSERT INTO SORIA_TPC.dbo.PERFILES (NOMBRE ) values ('Director')
INSERT INTO SORIA_TPC.dbo.PERFILES (NOMBRE ) values ('Docente')
INSERT INTO SORIA_TPC.dbo.PERFILES (NOMBRE ) values ('Secretario')

INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Cordero', '4725')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Bransen', '2587')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Pasteur', '2810')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('3 de Febrero', '1810')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Independencia', '30')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Av. Hipólito Yrigoyen', '288')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Miguel Cané', '4456')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Italia', '45')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Sin calle', '1')
INSERT INTO SORIA_TPC.dbo.DIRECCIONES (CALLE, NUMERO ) values ('Av. Siempre Viva', '123')

INSERT INTO SORIA_TPC.dbo.PERSONAS(Nombre,Apellido,DNI,Nacimiento,Email,IDDIRECCION)values('Maximiliano', 'Soria', '33293359', '1987-08-06', 'mes1407@gmail.com', 7)
INSERT INTO SORIA_TPC.dbo.PERSONAS(Nombre,Apellido,DNI,Nacimiento,Email,IDDIRECCION)values('Antonelia', 'Navarro', '36475321', '1990-08-08', 'anto.navarro@live.com.ar',8)
INSERT INTO SORIA_TPC.dbo.PERSONAS(Nombre,Apellido,DNI,Nacimiento,Email,IDDIRECCION)values('Ángel', 'Espinola', '40000000', '1996-03-08', 'aespinola@request.com',9)
INSERT INTO SORIA_TPC.dbo.PERSONAS(Nombre,Apellido,DNI,Nacimiento,Email,IDDIRECCION)values('Maximiliano','Sar Fernández','32000000','1986-06-08','msarfernandez@docentes.frgp.utn.edu.ar',10)
INSERT INTO SORIA_TPC.dbo.PERSONAS(Nombre,Apellido,DNI,Nacimiento,Email,IDDIRECCION)values('Ángel', 'Simón', '31000000', '1985-06-08', 'asimon@docentes.frgp.utn.edu.ar',10)
INSERT INTO SORIA_TPC.dbo.PERSONAS(Nombre,Apellido,DNI,Nacimiento,Email,IDDIRECCION)values('Tutor', 'Master', '10000000','1950-10-10', 'tmaster@email.com.ar',9)

INSERT INTO SORIA_TPC.dbo.ESTABLECIMIENTOS (NOMBRE, NUMERO, NIVEL, IDDIRECCION) values ('San José de Calasanz', 5, 'Primaria',1)
INSERT INTO SORIA_TPC.dbo.ESTABLECIMIENTOS (NOMBRE, NUMERO, NIVEL, IDDIRECCION) values ('Juan Bautista Alberdi', 21, 'Primaria',2)
INSERT INTO SORIA_TPC.dbo.ESTABLECIMIENTOS (NOMBRE, NUMERO, NIVEL, IDDIRECCION) values ('Gabriela Mistral', 27, 'Primaria',3)
INSERT INTO SORIA_TPC.dbo.ESTABLECIMIENTOS (NOMBRE, NUMERO, NIVEL, IDDIRECCION) values ('José Gervasio Artigas', 40,'Primaria',4)
INSERT INTO SORIA_TPC.dbo.ESTABLECIMIENTOS (NOMBRE, NUMERO, NIVEL, IDDIRECCION) values ('Escuela de la Patria mía', 48, 'Primaria',5)
INSERT INTO SORIA_TPC.dbo.ESTABLECIMIENTOS (NOMBRE, NIVEL, IDDIRECCION) values ('U.T.N.  F.R.G.P.', 'Facultad',6)

INSERT INTO SORIA_TPC.dbo.DOCENTES(IDPERSONA, NIVEL )values(2,'Primaria')
INSERT INTO SORIA_TPC.dbo.DOCENTES(IDPERSONA, NIVEL )values(4,'Facultad')
INSERT INTO SORIA_TPC.dbo.DOCENTES(IDPERSONA, NIVEL )values(5,'Facultad')

INSERT INTO SORIA_TPC.dbo.ALUMNOS (IDPERSONA, IDTUTOR )values(1,6),(3,6)

INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO) values ('1° A',1),('1° B',1),('1° C',1),('2° A',1),('2° B',1),('2° C',1),('3° A',1),('3° B',1),('3° C',1)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO) values ('4° A',2),('4° B',2),('4° C',2),('5° A',2),('5° B',2),('5° C',2),('6° A',2),('6° B',2),('6° C',2)

INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Matematica I',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Matematica II',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Estadística',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Inglés I',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Inglés II',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Programación I',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Laboratorio I',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Programación II',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Laboratorio II',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Programación III',3)
INSERT INTO SORIA_TPC.dbo.CURSOS (NOMBRE, CICLO ) values ('Laboratorio III',3)

INSERT INTO SORIA_TPC.dbo.USUARIOS (IDPERFIL,IDPERSONA,USERNAME,CONTRASEÑA,INICIO)values(1,4, 'MSF','111', GETDATE())
INSERT INTO SORIA_TPC.dbo.USUARIOS (IDPERFIL,IDPERSONA,USERNAME,CONTRASEÑA,INICIO)values(2,5,'ANGEL','222', GETDATE())
INSERT INTO SORIA_TPC.dbo.USUARIOS (IDPERFIL,IDPERSONA,USERNAME,CONTRASEÑA,INICIO)values(4,2, 'ANTO','333', GETDATE())

INSERT INTO SORIA_TPC.dbo.PERSONASxESTABLECIMIENTO(IDESTABLECIMIENTO,IDPERSONA)VALUES(5,2),(1,2),(6,4),(6,5)

INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO,IDDOCENTE)VALUES(1,1,1)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO)VALUES(5,4),(5,7),(5,10),(5,13),(5,16)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO,IDDOCENTE)VALUES(5,1,1)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO)VALUES(1,4),(1,7),(1,10),(1,13),(1,16)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO)VALUES(6,21),(6,22),(6,23)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO,IDDOCENTE)VALUES(6,24,2)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO)VALUES(6,25),(6,26),(6,27)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO,IDDOCENTE)VALUES(6,28,2)
INSERT INTO SORIA_TPC.dbo.CURSOSxESTABLECIMIENTO(IDESTABLECIMIENTO,IDCURSO)VALUES(6,29)